### ISSUE TITLE
Cannot install edgedriver (install.js issue)

### ISSUE THREAD

**Issue by ematta** [barretts/node-edgedriver#5]
When installing via nightwatch yeoman `yo nightwatchjs` I get the error below:

### Versions

```
node v7.5.0
npm v4.2.0
```

### Error

```
541 silly install printInstalled
542 verbose stack Error: edgedriver@2.1.142791 install: `node install.js`
542 verbose stack Exit status 1
542 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
542 verbose stack     at emitTwo (events.js:106:13)
542 verbose stack     at EventEmitter.emit (events.js:192:7)
542 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
542 verbose stack     at emitTwo (events.js:106:13)
542 verbose stack     at ChildProcess.emit (events.js:192:7)
542 verbose stack     at maybeClose (internal/child_process.js:890:16)
542 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
543 verbose pkgid edgedriver@2.1.142791
544 verbose cwd /Users/.../code/.../e2e
545 error Darwin 14.5.0
546 error argv "/usr/local/Cellar/node/7.5.0/bin/node" "/usr/local/bin/npm" "install"
547 error node v7.5.0
548 error npm  v4.2.0
549 error code ELIFECYCLE
550 error errno 1
551 error edgedriver@2.1.142791 install: `node install.js`
551 error Exit status 1
552 error Failed at the edgedriver@2.1.142791 install script 'node install.js'.
552 error Make sure you have the latest version of node.js and npm installed.
552 error If you do, this is most likely a problem with the edgedriver package,
552 error not with npm itself.
552 error Tell the author that this fails on your system:
552 error     node install.js
552 error You can get information on how to open an issue for this project with:
552 error     npm bugs edgedriver
552 error Or if that isn't available, you can get their info via:
552 error     npm owner ls edgedriver
552 error There is likely additional logging output above.
553 verbose exit [ 1, true ]
```

**Comment by Fishbowler** [comment]
Any chance you're trying this on a Mac? This package is only suitable for Windows.
